lib_LTLIBRARIES = libtraceprov.la
libtraceprov_la_SOURCES = traceprov.c file_utils.c utils.c traceprov_duckdb_infer.cpp

AM_CFLAGS = -I${SMOKEDDUCK_INCUDE_PATH} -DTRACEPROV_PAGE_SIZE_RAW=${TRACEPROV_PAGE_SIZE} -UPACKAGE_NAME -UPACKAGE_VERSION -UPACKAGE_STRING -UPACKAGE_BUGREPORT -UPACKAGE_URL -UPACKAGE_TARNAME -UPACKAGE_URL
AM_CPPFLAGS = -I${SMOKEDDUCK_INCUDE_PATH} -DTRACEPROV_PAGE_SIZE_RAW=${TRACEPROV_PAGE_SIZE} -UPACKAGE_NAME -UPACKAGE_VERSION -UPACKAGE_STRING -UPACKAGE_BUGREPORT -UPACKAGE_URL -UPACKAGE_TARNAME -UPACKAGE_URL
libtraceprov_la_LIBADD = -lduckdb
libtraceprov_la_LDFLAGS = -L${SMOKEDDUCK_PATH} -Wl,-rpath,${SMOKEDDUCK_PATH}
bin_PROGRAMS = run_smokedduck
run_smokedduck_SOURCES = run_duckdb_query.cpp
run_smokedduck_LDADD = -lduckdb libtraceprov.la
run_smokedduck_LDFLAGS = -L${SMOKEDDUCK_PATH} -Wl,-rpath,${SMOKEDDUCK_PATH}
if ENABLE_SD_MODE
AM_CFLAGS += -DTRACEPROV_SD_MODE=1
AM_CPPFLAGS += -DTRACEPROV_SD_MODE=1
endif